import pandas as pd

def generate_audit_report(
    dataset_name: str,
    df_shape: tuple,
    target_col: str,
    sensitive_col: str,
    model_type: str,
    accuracy: float,
    metrics: dict,
    risk_level: str,
    explanation: str,
    mitigation: str
) -> str:
    """
    Generate a downloadable fairness audit report in Markdown format.
    """
    
    report = f"""# AI Fairness Audit Report

## 1. Dataset Summary
- **Dataset Name:** {dataset_name}
- **Number of Rows:** {df_shape[0]}
- **Number of Columns:** {df_shape[1]}
- **Target Prediction Column:** {target_col}
- **Sensitive Attribute Column:** {sensitive_col}

## 2. Model Performance
- **Model Trained:** {model_type}
- **Accuracy:** {accuracy:.4f}

## 3. Fairness Metrics & Risk Assessment
- **Demographic Parity Difference:** {metrics.get('demographic_parity_difference', 0):.4f}
- **Equal Opportunity Difference:** {metrics.get('equal_opportunity_difference', 0):.4f}
- **Overall Bias Risk Level:** **{risk_level}**

## 4. AI-Generated Bias Explanation
{explanation}

## 5. Recommended Mitigation Strategies
{mitigation}

---
*Report generated by the AI Fairness Auditing System.*
"""
    return report
